#!/usr/bin/env python3

from __future__ import annotations

import json
import pathlib
import sys
from datetime import datetime, timezone

EXCLUDED_MODELS = {"bakllava:latest", "gpt-oss:20b"}

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "resources" / "ollama-nodes.json"

def tps(server: dict) -> float:
    raw = (server.get("performance") or {}).get("tokens_per_second")
    try:
        return float(raw)
    except (TypeError, ValueError):
        return 0.0

def main() -> int:
    try:
        from ollamafreeapi import OllamaFreeAPI
    except ImportError:
        print("pip install ollamafreeapi", file=sys.stderr)
        return 1

    client = OllamaFreeAPI()
    models = sorted(set(client.list_models()) - EXCLUDED_MODELS)

    nodes: dict[str, list[dict]] = {}
    for model in models:
        try:
            servers = client.get_model_servers(model)
        except Exception as error:
            print(f"  ! {model}: {type(error).__name__}: {error}", file=sys.stderr)
            continue

        entries = [
            {
                "url": server["url"],
                "tps": tps(server),
                "location": ", ".join(
                    part
                    for part in (
                        (server.get("location") or {}).get("city"),
                        (server.get("location") or {}).get("country"),
                    )
                    if part
                )
                or "unknown",
                "organization": (server.get("organization") or "unknown"),
                "lastTested": (server.get("performance") or {}).get("last_tested"),
            }
            for server in servers
        ]
        entries.sort(key=lambda entry: entry["tps"], reverse=True)
        if entries:
            nodes[model] = entries
        print(f"  {model}: {len(entries)} node(s)")

    document = {
        "$comment": (
            "GENERATED by scripts/refresh-nodes.py from the ollamafreeapi catalog "
            "(github.com/mfoud444/ollamafreeapi, MIT). Do not edit by hand. "
            "These are free community nodes: availability and latency vary, and "
            "lastTested may be far in the past. The runtime treats every entry as "
            "a candidate to be health-checked, never as a guarantee."
        ),
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "source": "https://github.com/mfoud444/ollamafreeapi",
        "nodes": nodes,
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(nodes)} models)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
